### ISSUE TITLE
The meaning of values in 'config_speed.txt'

### ISSUE THREAD

**Issue by xlcbingo1999** [pengyanghua/DL2#2]
For example, I want to know the meaning of line 82 in  'config_speed.txt':
I know it's a job of training 'resnet-50', but what's the meaning of 32, 7, 10? 
And WHAT's the meaning of the following 10 items' array, 7 items' array and final 10 items' array?
Thanks for your help~
```
('resnet-50', 'dist_sync', 32, 7, 10, [2.85, 2.85, 2.138, 2.138, 2.138, 2.138, 2.138, 2.138, 2.138, 2.138], [1.94, 0.832, 1.07, 0.947, 1.188, 1.386, 1.6], [0.507, 0.498, 0.509, 0.526, 0.614, 0.61, 0.517, 0.492, 0.493, 0.517])
```

**Comment by pengyanghua** [comment]
@xlcbingo1999 Check the meaning here https://github.com/pengyanghua/DL2/blob/main/speed.py#L19

**Comment by xlcbingo1999** [comment]
> @xlcbingo1999 Check the meaning here https://github.com/pengyanghua/DL2/blob/main/speed.py#L19

Thanks for your help!
