### ISSUE TITLE
trained model request

### ISSUE THREAD

**Issue by vihowe** [pengyanghua/DL2#4]
Sorry, I have try to train the RL model in online learning manner. But after 1000000 steps training, the final model performs not well. Could I download your model check point? Or, could you please tell me something I should pay attention to?

Thanks a lot.

**Comment by pengyanghua** [comment]
@vihowe Hi, I do not have model checkpoint on hand now. For the training, the number of training steps depends on your trace size and DNN size. Maybe you do not need to train 1000000 steps. Also, you can try hyper-parameters search to find the best ones.
